### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by zoldaten** [strayge/rutracker_parser#6]
Hi! Thanks for fixing, but still cant go on with start string:
python ./loader.py --user *** --password ***  --ids 0000001 5160000 --threads 2 --qsize 25 --resume

Here`s a traceback -

Traceback (most recent call last):
  File "./loader.py", line 83, in <module>
    proxy = settings.get_free_proxy()
  File "D:\downloads\1\rutracker_parser-master\settings.py", line 240, in get_fr
ee_proxy
    not_using_proxies = [proxy for proxy in self.proxy_list if proxy['in_use'] <
 self.threads_per_proxy]
  File "D:\downloads\1\rutracker_parser-master\settings.py", line 240, in <listc
omp>
    not_using_proxies = [proxy for proxy in self.proxy_list if proxy['in_use'] <
 self.threads_per_proxy]
TypeError: string indices must be integers
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\python3\lib\multiprocessing\util.py", line 319, in _exit_function
    p.join()
  File "C:\python3\lib\multiprocessing\process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "C:\python3\lib\multiprocessing\popen_spawn_win32.py", line 80, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt

**Comment by strayge** [comment]
are proxy set in `proxy.txt`?   
with correct format?
```
127.0.0.1 8080
127.0.0.1 8081
```

**Comment by zoldaten** [comment]
ok, i started it up, but nothing`s happening when it goes on:

========== Program started ==========
2021-10-30 21:28:11,409 __main__        INFO    numbers of threads: 2
2021-10-30 21:28:11,439 settings        INFO    loaded 2 proxies from file
2021-10-30 21:28:11,519 settings        INFO    loaded 1 login
2021-10-30 21:28:12,299 settings        INFO    input:          5159999
2021-10-30 21:28:12,299 settings        INFO    finished:       0
2021-10-30 21:28:12,299 settings        INFO    left:           5159999
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"
2021-10-30 21:28:13,409 __main__        INFO    free proxy not available
2021-10-30 21:28:14,409 __main__        ERROR   processing loop. cookie - error:
 request exception
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"
2021-10-30 21:29:14,409 __main__        INFO    free proxy not available
Last 10 sec:   0 - OK,   0 - NOHASH,  0 - ERROR, Remaining: 5159k, 0:00"

Perhaps, links to rutracker should be checked in parse.py ?

**Comment by strayge** [comment]
You got some error during login.
Check what exception you got at get_cookie in parse.py

**Comment by zoldaten** [comment]
aaa...site is blocked by Regulator. may i just change links to the site (i mean rutracker -> rutracker.mirror or somewhat ?) in parse ?

**Comment by strayge** [comment]
You can try mirror, should work.
Other way is get proxies from which is non-blocked (tor also work as proxy)
